# Generated by Django 5.0.1 on 2024-02-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
